import {
  HomeIcon,
  ChartBarIcon,
  DocumentChartBarIcon,
  ChartPieIcon,
  UserGroupIcon,
  AcademicCapIcon,
  CurrencyDollarIcon,
  EnvelopeIcon,
  PhoneIcon,
  UsersIcon,
  CalculatorIcon,
  CubeIcon,
  Cog6ToothIcon,
  UserCircleIcon,
  CreditCardIcon,
  CurrencyEuroIcon,
  DocumentTextIcon,
  ClipboardDocumentIcon,
  BanknotesIcon,
  ScaleIcon,
  DocumentIcon,
  PencilSquareIcon,
  Squares2X2Icon,
  BookOpenIcon,
  ChartBarSquareIcon,
  ArrowTrendingUpIcon,
  DocumentCurrencyRupeeIcon,
} from "@heroicons/react/24/outline";


export const IconMapper = {
  HomeIcon: <HomeIcon className="h-5 w-5" />,
  ChartBarIcon: <ChartBarIcon className="h-5 w-5" />,
  DocumentChartBarIcon: <DocumentChartBarIcon className="h-5 w-5" />,
  ChartPieIcon: <ChartPieIcon className="h-5 w-5" />,
  UserGroupIcon: <UserGroupIcon className="h-5 w-5" />,
  AcademicCapIcon: <AcademicCapIcon className="h-5 w-5" />,
  CurrencyDollarIcon: <CurrencyDollarIcon className="h-5 w-5" />,
  EnvelopeIcon: <EnvelopeIcon className="h-5 w-5" />,
  PhoneIcon: <PhoneIcon className="h-5 w-5" />,
  UserIcon: <UsersIcon className="h-5 w-5" />,
  CalculatorIcon: <CalculatorIcon className="h-5 w-5" />,
  CubeIcon: <CubeIcon className="h-5 w-5" />,
  Cog6ToothIcon: <Cog6ToothIcon className="h-5 w-5" />,
  UserCircleIcon: <UserCircleIcon className="h-5 w-5" />,
  CreditCardIcon: <CreditCardIcon className="h-5 w-5" />,
  CurrencyEuroIcon: <CurrencyEuroIcon className="h-5 w-5" />,
  DocumentTextIcon: <DocumentTextIcon className="h-5 w-5" />,
  ClipboardDocumentIcon: <ClipboardDocumentIcon className="h-5 w-5" />,
  BanknotesIcon: <BanknotesIcon className="h-5 w-5" />,
  ScaleIcon: <ScaleIcon className="h-5 w-5" />,
  DocumentIcon: <DocumentIcon className="h-5 w-5" />,
  PencilSquareIcon: <PencilSquareIcon className="h-5 w-5" />,
  Squares2X2Icon: <Squares2X2Icon className="h-5 w-5" />,
  BookOpenIcon: <BookOpenIcon className="h-5 w-5" />,
  ChartBarSquareIcon: <ChartBarSquareIcon className="h-5 w-5" />,
  TrendingUpIcon: <ArrowTrendingUpIcon className="h-5 w-5" />,
  DocumentReportIcon: <DocumentCurrencyRupeeIcon className="h-5 w-5" />,
};
